#!/usr/bin/env node
// Build the PR-description corpus from public repositories via the
// unauthenticated GitHub REST API, and vendor the natural-writing skill text
// at a pinned commit. Output is fixtures/prs.json and fixtures/natural-writing-skill.md.
//
//   node tools/typesafe-loop/writing/build-corpus.mjs

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const REPOS = ["luka-zivkovic/coeval", "luka-zivkovic/ironside", "luka-zivkovic/dailies", "luka-zivkovic/casefile", "luka-zivkovic/overclock"];
const SKILL_PATH = "plugins/natural-writing/skills/natural-writing/SKILL.md";
const MIN_CHARS = 300;

async function getJson(url) {
  const response = await fetch(url, { headers: { Accept: "application/vnd.github+json", "User-Agent": "typesafe-loop-corpus" } });
  if (!response.ok) throw new Error(`${url}: ${response.status}`);
  return response.json();
}

// In a Claude Code cloud session the GitHub proxy serves API reads only for
// repositories attached to the session, so an unattached public repo answers
// 403 there while answering 200 from a laptop. Skip it and say so.
async function listPulls(repo, page) {
  try {
    return await getJson(`https://api.github.com/repos/${repo}/pulls?state=all&per_page=100&page=${page}`);
  } catch (error) {
    if (/: 403$/.test(String(error.message))) { console.warn(`skipping ${repo}: 403 (not attached to this session?)`); return null; }
    throw error;
  }
}

/** Remove generator footers and collapsed HTML so only the human-facing prose remains. */
export function cleanBody(body) {
  return String(body ?? "")
    .replace(/🤖 Generated with \[Claude Code\]\([^)]*\)\s*/g, "")
    .replace(/https:\/\/claude\.ai\/code\/session_\w+\s*/g, "")
    .replace(/---\s*_Generated by \[Claude Code\]\([^)]*\)_\s*/g, "")
    .replace(/<details>[\s\S]*?<\/details>/gi, "")
    .replace(/\[\/\/\]: # \([^)]*\)\s*/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/** Prose units: sentences plus bullet lines, since PR bodies are often lists without terminal periods. */
export function sentenceCount(text) {
  const sentences = (text.match(/[.!?](\s|$)/g) ?? []).length;
  const bullets = (text.match(/^\s*[-*]\s+\S/gm) ?? []).length;
  return sentences + bullets;
}

async function main() {
  const out = [];
  for (const repo of REPOS) {
    for (let page = 1; page <= 5; page += 1) {
      const pulls = await listPulls(repo, page);
      if (!pulls || pulls.length === 0) break;
      for (const pr of pulls) {
        if (/\[bot\]$/.test(pr.user?.login ?? "")) continue;
        const body = cleanBody(pr.body);
        if (body.length < MIN_CHARS || sentenceCount(body) < 3) continue;
        out.push({
          id: `${repo.split("/")[1]}#${pr.number}`,
          repo,
          number: pr.number,
          title: pr.title,
          url: pr.html_url,
          author: pr.user?.login ?? null,
          merged: Boolean(pr.merged_at),
          createdAt: pr.created_at,
          body
        });
      }
      if (pulls.length < 100) break;
    }
  }
  out.sort((a, b) => a.id.localeCompare(b.id));
  await mkdir(path.join(here, "fixtures"), { recursive: true });
  await writeFile(path.join(here, "fixtures", "prs.json"), JSON.stringify({ builtAt: new Date().toISOString(), repos: [...new Set(out.map((c) => c.repo))], minChars: MIN_CHARS, count: out.length, cases: out }, null, 2));
  // Skill text: resolve the latest commit touching it, fetch raw at that sha, fall back
  // to the default branches, and if everything fails keep the vendored copy already on disk.
  let pinned = null;
  const refs = [];
  try { refs.push((await getJson(`https://api.github.com/repos/luka-zivkovic/overclock/commits?path=${SKILL_PATH}&per_page=1`))[0]?.sha); } catch { /* unattached in a cloud session */ }
  refs.push("main", "master");
  for (const ref of refs.filter(Boolean)) {
    const response = await fetch(`https://raw.githubusercontent.com/luka-zivkovic/overclock/${ref}/${SKILL_PATH}`);
    if (response.ok) { pinned = ref; await writeFile(path.join(here, "fixtures", "natural-writing-skill.md"), `<!-- vendored from luka-zivkovic/overclock@${ref} ${SKILL_PATH} -->\n${await response.text()}`); break; }
  }
  if (!pinned) console.warn("could not fetch the skill text; keeping the vendored fixtures/natural-writing-skill.md (see its header for the pinned commit)");
  console.log(`${out.length} PR bodies from ${[...new Set(out.map((c) => c.repo))].length} repos; skill ${pinned ? `pinned at ${pinned.slice(0, 7)}` : "kept from disk"}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => { console.error(error); process.exitCode = 1; });
}
